[package]
name = "atap"
version = "0.1.0"
edition = "2024"

[features]
tls = ["dep:rustls", "dep:rustls-platform-verifier"]

[dependencies]
libc = "0.2.186"

rustls = { version = "0.23.44", optional = true, default-features = false, features = [
    "std",
    "aws_lc_rs",
    "tls12",
    "prefer-post-quantum",
] }

rustls-platform-verifier = { version = "0.7", optional = true }

[dev-dependencies]
libc = "0.2.186"

rcgen = { version = "0.14", default-features = false, features = ["crypto", "pem", "aws_lc_rs"] }

time = "0.3"
